version: '3.8'

services:
  web:
    build: ./app
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_NAME: flaskappdb
      DB_USER: flaskappuser
      DB_PASSWORD: flaskpass
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: flaskappdb
      POSTGRES_USER: flaskappuser
      POSTGRES_PASSWORD: flaskpass
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
